sudo: required
dist: trusty
language: node_js
node_js:
  - 'node'

branches:
  only:
    - master

addons:
apt:
  sources:
    - google-chrome
  packages:
    - google-chrome-stable
    - google-chrome-beta

before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install -g angular-cli@webpack
  - npm install -g karma
  - npm install

before_script:
- ng build

script:
- ng test --watch false
